### ISSUE TITLE
The socket closes each time when emit a log record

### ISSUE THREAD

**Issue by dvazar** [cdumay/djehouty#10]
The return value of the `select.select` function is a triple of lists of objects that are ready: subsets of the first three arguments, not just `rlist`.
https://github.com/ovh/djehouty/blob/7cb1d3569fbd92b5697bc10e8a5bd95049679ccc/src/djehouty/tcp.py#L61-L72
Therefore, checking the condition `len (rlist)> 0` in this case will always return a value greater than zero. As a consequence, the function `checkSocket` will always return `False`, since `rlist [0] .recv_into (data, 1024)` always raises the `AttributeError` exception.
https://github.com/ovh/djehouty/blob/7cb1d3569fbd92b5697bc10e8a5bd95049679ccc/src/djehouty/tcp.py#L77-L82
Thus, the `emit` function will always close the socket, before sending the next portion of logs.

Fixed in #9

**Comment by cdumay** [comment]
Good catch! Thank you!
